PUT http://localhost:3000/api/updateMany/Office
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InByZWZlcmVuY2VzIjp7ImRhcmtUaGVtZSI6ZmFsc2V9LCJfaWQiOiI2MGQ0ZDM5MDk2YmQxZDBhZDgwOTBkMTQiLCJmaXJzdE5hbWUiOiJFZGdhciIsImxhc3ROYW1lIjoiUGFydWNobyIsImlkRG9jdW1lbnQiOiIyMDgyNjYxOSIsImJpcnRoZGF5IjoiMjAyMS0wNi0xNSIsImRlcGFydG1lbnQiOiJPcGVyYWNpb25lcyIsImNvbXBhbnlQb3NpdGlvbiI6IlN1cGVydmlzb3IgZGUgSGVscCBEZXNrIiwidXNlclJvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZW1haWwiOiJlLnBhcnVjaG9AbWljcm9maWxtc2NlbnRlcmphaGEuY29tIiwidXNlclBhc3N3b3JkIjpudWxsLCJfX3YiOjB9LCJpYXQiOjE2MjU5NzQ3OTl9.pUnYxvT1MO9-_q7NwfMgMgAp6_3Ov8ljU4hLLxnH3F0
# auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRmluZGVkIjp7InByZWZlcmVuY2VzIjp7ImRhcmtUaGVtZSI6ZmFsc2V9LCJfaWQiOiI2MGQ0ZDM5MDk2YmQxZDBhZDgwOTBkMTQiLCJmaXJzdE5hbWUiOiJFZGdhciIsImxhc3ROYW1lIjoiUGFydWNobyIsImlkRG9jdW1lbnQiOiIyMDgyNjYxOSIsImJpcnRoZGF5IjoiMjAyMS0wNi0xNSIsImRlcGFydG1lbnQiOiJPcGVyYWNpb25lcyIsImNvbXBhbnlQb3NpdGlvbiI6IlN1cGVydmlzb3IgZGUgSGVscCBEZXNrIiwidXNlclJvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZW1haWwiOiJlLnBhcnVjaG9AbWljcm9maWxtc2NlbnRlcmphaGEuY29tIiwidXNlclBhc3N3b3JkIjpudWxsLCJfX3YiOjB9LCJpYXQiOjE2MjU5NjQ1NDh9.aghQWNDJXhYCyF8BEtRu4urGnrsFGvPFL4tSSQlF_3s
Content-Type: application/json

{
  "filter": { "inventory.productType": "Lectora de cheques" },
  "body": { "inventory.$[element]": "Lectora de cheques (editado)" }
}
